{% set name = "omniscidb-cpu" %}
{% set version = "4.6.1" %}
{% set sha256 = "04d69fd4b5d48e4bff937ad9c149c8a98746d54263485fcc3b840a4682bdda0d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/omnisci/omniscidb/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}   # [linux] required for C++ headers (when using clang)
    - {{ compiler('c') }}     # [linux] (when using gcc, disable it when switching to clang)
    - cmake
    - make
    - maven
    - openjdk 8.*
    - wget
    - clangdev
    - go
    - bisonpp
  host:
    - snappy
    - arrow-cpp
    - blosc
    - boost-cpp
    - double-conversion
    - libgdal 2.*  # with libgdal-3 one ImportTest fails
    - flex
    - gflags
    - glog 0.3.*  # with glog 0.4 omniscidb 4.6.1 build fails, remove this restriction when upgrading omniscidb
    - libarchive
    - libkml
    - libpng
    - llvmdev
    - clangdev  # required here for clang 8 support
    - openssl
    - parquet-cpp
    - thrift-cpp >=0.11.0
    - ncurses
  run:
    - snappy
    - boost-cpp
    - double-conversion
    - libgdal 2.*
    - glog 0.3.*  # see comment above
    - gflags
    - openjdk 8.*
    - ncurses
    - xz
    - bzip2
    - zlib
about:
  home: https://www.omnisci.com/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: 'The OmniSci database'

  description: |
    OmniSciDB is an in-memory, column store, SQL relational database 
    that was designed from the ground up to run on GPUs.
  doc_url: https://www.omnisci.com/docs/latest/
  dev_url: https://github.com/omnisci/omniscidb

extra:
  recipe-maintainers:
    - xmnlab
    - pearu
    - andrewseidl
