{% set name = "omniscidb-cpu" %}
{% set version = "4.7.0" %}
{% set sha256 = "00e4937ca15a13658e24bc18dd0468dd4820cf02a3d014161ac8cc9c6c7d3d1c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/omnisci/omniscidb/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}   # [linux] required for C++ headers (when using clang)
    - {{ compiler('c') }}     # [linux] (when using gcc, disable it when switching to clang)
    - cmake
    - make
    - maven
    - openjdk 8.*
    - wget
    - clangdev      # [linux] llvm 8 is ok when using gcc as compiler
    - clangdev 7.*  # [osx] using clang 8 as compiler, many tests fail 
    - go
    - bisonpp
  host:
    - snappy
    - arrow-cpp >=0.12.1
    - blosc
    - boost-cpp 1.68.*
    - double-conversion
    - libgdal 2.*   # with libgdal-3 one ImportTest fails
    - flex
    - gflags
    - glog
    - libarchive
    - libkml
    - libpng
    - llvmdev       # [linux]
    - clangdev      # [linux], required here for clang/llvm 8 support
    - llvmdev 7.*   # [osx], see above
    - clangdev 7.*  # [osx], see above
    - openssl
    - thrift-cpp >=0.11.0
    - ncurses
  run:
    - snappy
    - boost-cpp 1.68.*
    - double-conversion
    - libgdal 2.*
    - glog
    - gflags
    - openjdk 8.*
    - ncurses
    - xz
    - bzip2
    - zlib
    # omnscidb server calls clang++ in runtime for UDF support, hence,
    # should we include clangdev (and compiler('cxx')) dependency
    # here?

about:
  home: https://www.omnisci.com/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: 'The OmniSci database'

  description: |
    OmniSciDB is an in-memory, column store, SQL relational database 
    that was designed from the ground up to run on GPUs.
  doc_url: https://www.omnisci.com/docs/latest/
  dev_url: https://github.com/omnisci/omniscidb

extra:
  recipe-maintainers:
    - xmnlab
    - pearu
    - andrewseidl
