travis:
  secure:
    BINSTAR_TOKEN: CgAXqRdLyUK4Bz6QdeTOKQ9DCxH4EU7cVKPT+yv77xM8uF8ZsQVu6u+LpWJljM5FnJNHjNw0MGg6gvCkKgE2DubGupU2F3goleBdJlXgK0Od9tcJHD5V0j9TBnDQtjWukXwzFyOiyicG8w/KIazqhOnV2exq5sxMYbJPyzhQN3iAuLugu8clvvAR0fhOrf8M0Lww8+eXbWsVlRSUKXt19nqKF1lCircQhKuovrMq35XFJHJ+FKrJPxlCQoD4ZwyHQCZZmS8tuKZxi02HBpXprWYQdIJ8IeSmEz5xzpbJrUwwv/Cwr615lxFY/k25jR+N5JP33gCtcyl8PYmTiLSAhhoTjrZ7FcwBZIhR7JZg+e1i66fEAvNUr7RMZKI8uCszTotoNghYo/kA34O5eTBpiesw3HYrlVeT03pyUYjGNKFW/+9a0jAYzaFTqHxnTFMo+gJJHin0+cXMR41TOwAoepPvWlUOG3WfU6I+dy3q+OZ4UaC+paJB7cm4k+niKDPdG/tOCVCG9LLt1bZreOYgg/WzGS3pYyXfhmZbKpbg6frSf7iDoq6sHhR0EtbETqE/7tpMRETIMog4lIO7lYzrAsyl1oCRX3diJYMWNV2ousG6w5htuywKt8NFyXyptzQwXOhkNBGvlUXzHD+cF4+TiZiYQhJQHrxafW5WgsJCsGs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
